# Basic
title: zzhpeng
subtitle: æ—¥å¸¸æ¬ç –
description: æ¬ç –è·¯æ¼«æ¼«~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: zzhpeng
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: php / webå¼€å‘
url: "http://zzhpeng.com.cn"

# Comment
comment:
    gitment: 1
    # uyan: 0  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·
    # disqus: 0

# Social
social:
    weibo: 5366874726 
    github: fromChinaBoy
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: 2ada30d8d0f7
    # twitter: 
    mail: zhangzhenpeng008@gmail.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: xxxx  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: xxxx  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #ffffff

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: blog

# Navigation buttons in the front page.s
nav:
    - {title: all, description: archive, url: '/archive'}
    - {title: tags, description: tags, url: '/tags'}
    - {title: about me, description: about, url: '/about'}
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


